SUBDIRS = library \
	  library2 \
	  executable \
	  multiple_languages \
	  generated_source \
	  source_subdirs \
	  library_file_dependencies \
	  set_library_name \
	  script \
	  xs \
	  create_dirs \
	  libraries_needing_libraries

CXXFLAGS += -D__GLOBAL_DEFINE__ -fPIC

include ../bs.mk
