ifndef BS__INIT_MK
BS__INIT_MK=1

BUILDDIR ?= build
TMPDIR ?= intermediate

TARGET_VARIABLES = CXXFLAGS LDFLAGS SOURCES LIBRARIES
SUBDIR_VARIABLES = CXXFLAGS LDFLAGS DSOS EXECUTABLES

DIRS += $(BUILDDIR) $(TMPDIR) $(BUILDDIR)/lib $(BUILDDIR)/bin

# Default values for variables that can later be added to
CPPFLAGS = -I.

endif
