ifndef BS__INIT_MK
BS__INIT_MK=1

BUILDDIR ?= build
TMPDIR ?= intermediate

PER_TARGET_VARIABLES = CXXFLAGS LDFLAGS SOURCES
SUBDIR_VARIABLES = CXXFLAGS LDFLAGS

DIRS += $(BUILDDIR) $(TMPDIR) $(BUILDDIR)/lib


endif
