ifndef BS__TARGETS_CREATE_DIR_MK
BS__TARGETS_CREATE_DIR_MK=1

_BS_SUPPORTED_TARGETS += CREATE_DIR

_BS_DEFAULT_OUTPUT_CREATE_DIR = $(1)

define _BS_TARGET_RULE_CREATE_DIR

$(_BS_BUILD_TARGET_$(1)):
	mkdir -p $$@

endef

endif
